services:
  mysql:
    image: mysql:8.0
    container_name: stream_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stream_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - stream_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: stream_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - stream_network

volumes:
  db:

networks:
  stream_network:
    driver: bridge